version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws --version
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 670543300056.dkr.ecr.ap-northeast-2.amazonaws.com
      - npm install yarn
  build:
    commands:
      - docker build -t monitoring-api .
  post_build:
    commands:
      - docker tag monitoring-api:latest 670543300056.dkr.ecr.ap-northeast-2.amazonaws.com/monitoring-api:latest
      - docker push 670543300056.dkr.ecr.ap-northeast-2.amazonaws.com/monitoring-api:latest
      - echo Writing image definitions file...
      - printf '[{"name":"monitoring-api-container","imageUri":"%s"}]' 670543300056.dkr.ecr.ap-northeast-2.amazonaws.com/monitoring-api:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json