name: run-pytest
on: push

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install requirements
        run: cd backend && pip install -r requirements.txt
      - name: Run test
        run: pytest